### ISSUE TITLE
Many-To-Many field doesn't "get" changed values 0.9.5.5

### ISSUE THREAD

**Issue by raeldc** [jonathangeiger/kohana-jelly#33] opened 2010-03-03 07:37 UTC
I don't know how to properly entitle this bug so keep reading.

When you change a many-to-many field, the values are in the `_changed` property but it can't be accessed using `get()`. `get()` will always display the values from the database.

I'm not sure if this is the same with other relationship fields but I'm working with Many-to-Many (user:roles).

This bug becomes apparent when you try to submit a form to edit an object, in my case: a user manager where I change the roles of a user.

If the validation fails, I re-display the form loading the changed values with it from $_POST. Other fields display the changed values, but the many-to-many(select multiple) doesn't. It still loads the values that are from the database.

A simpler code to test this bug is this:

```
$user = Jelly::select('user')->where('username', '=', 'testuser')->limit(1)->load();

//user currently has roles 1 and 2. let's change it to 3 and 4.
$user->set(array('roles' => array(3,4)));

//this will display role 1 and 2 even if you've already set 3 and 4 as the new roles.
foreach ($user->roles as $role) 
{
    echo Kohana::debug($role);
}
```

Thanks!

**Comment by banks** [comment] 2010-03-03 08:57
Can you confirm if this changed as of 0.9.5.5 or whether this is has been around for a while? Jon - do the unittests cover `set()`, `add()` and `remove()` form n:many relations? We should certainly put some tests in to cover these case if not.

**Comment by banks** [comment] 2010-03-03 09:03
Ahh, ManyToMany changed in the last tag (see [c6b604e7e4](http://github.com/jonathangeiger/kohana-jelly/commit/c6b604e7e4a157c44aa39df763ea1186cb59c7ee#diff-3).

Not sure if this relates to your issue?

**Comment by raeldc** [comment] 2010-03-03 09:39
I checked out to the earliest commits. Seems that the problem has always been there. And I didn't see anything in c6b604e7e4 that would have caused the problem.

**Comment by banks** [comment] 2010-03-03 11:34
Thanks raeldc, We'll have a look. If you can spot the cause of the problem, let us know.

**Comment by jonathangeiger** [comment] 2010-03-03 12:28
Closed by d5a8cde6be97e9da9d87714b5af4a27bbd30b18c. Thanks raeldc!

**Comment by jonathangeiger** [comment] 2010-03-03 12:28
> Jon - do the unittests cover set(), add() and remove()  form n:many relations?

No, they're kind of sparse at the moment. I'm going to dedicate some time to adding more unit tests to hopefully catch these things. Although this bug hasn't probably been in Jelly since the beginning!

**Closed as completed by jonathangeiger** 2010-03-03 12:28 UTC
Labels: Bug

**Comment by raeldc** [comment] 2010-03-03 13:35
Thanks Jon! It's awesome how you respond to these issues so quick :).

**Comment by jonathangeiger** [comment] 2010-03-03 15:08
Just so you know, this also affected HasMany and HasOne, so I've fixed that as well.

9d96346d24bdc6d996ea10613c7f5103f2469443
