### ISSUE TITLE
Is it possible to use $this for validation callbacks?

### ISSUE THREAD

**Issue by Lokaltog** [jonathangeiger/kohana-jelly#86] opened 2010-03-29 17:14 UTC
I'm currently working on an image uploading module that requires some custom validation. I'm using `identify` from ImageMagick to identify the image type and dimensions. I want to avoid calling identify twice (both in the validation callback and in the save method) for performance reasons, so I figured I could store the image details in the object when the callback is executed and re-use the data in the `save()` method.

The problem is that `initialize()` is static, so I can't create a callback that uses `$this`. I want to avoid using static variables for this, is there any way to use `$this` when defining callbacks?

**Comment by banks** [comment] 2010-03-29 18:26
Probably not.

I guess off the top of my head the best way to do this would be to have a singleton library that stores the results of the function in any given script execution for a modelID/imagefile or some other ID so you can use a static callback.

This isn't a particularly nice solution but I'm not sure what viable alternatives there are.

The other option is to not call validate() separately. Do you really need to do this? Could you just call save and ctch the exception or do you need to validate and save separately?

**Comment by Lokaltog** [comment] 2010-03-29 20:01
I'm not calling `validate()` separately, I was hoping that the one call that's inside `save()` was enough (that's why I want to use callbacks for this). I need to make sure that the images are valid (extension validation isn't enough), and I need the dimensions of the images. That's why I use identify.

I'm not sure if I do this the "right" way, but this is the best solution I've found so far:

```
class Model_Image extends Jelly_Model {
    public static function initialize(Jelly_Meta $meta) {
        $meta->fields(array(
            // ...
            'file' => new Field_File(array(
                'in_db' => false,
                'path' => '/tmp',
                'rules' => array(
                    'Upload::not_empty' => array(),
                    'Upload::valid' => array(),
                    'Upload::size' => array('4M'),
                    'Upload::type' => array('Upload::type' => self::$types),
                ),
            )),
            // ...
        ));
    }
    public function save($key = null) {
        // Perform image verification with identify here
        // Image dimensions are also fetched here
        parent::save($key);
    }
}
```

This almost works, except for two new problems:
1. I have to call `parent::save()` _after_ I validate the images. That means that I can't take advantage of the "pre-checks" of the upload (Upload::valid, etc.), so I have to move these rules out of the `Jelly_Meta` object and into the `save()` method above, and
2. If I move validation into the `save()` method like the example above, I can't trigger a `Validation_Exception` because I don't have a Validate object. I can throw a regular Exception, but then I have to catch the two exception types separately even though they indicate the same problem (invalid data).

Please let me know if you have any suggestions to how I could solve this.

Also, why is `initialize()` declared static in the first place? I'm sure there's a good reason for it, I'm just curious. :)

**Comment by jonathangeiger** [comment] 2010-03-30 01:59
> Also, why is initialize() declared static in the first place? I'm sure there's a good reason for it, I'm just curious. :)

It's by design and mostly for performance reasons. Metadata is only created once, not at every object instantiation. 

Would it be worth it to pass the entire object in the data for callbacks? I know this won't work for rules or filters. Another option is to have a specific value like :this which is converted to $this before passing the rules/filters/callbacks along to the validation object.

**Comment by Lokaltog** [comment] 2010-03-30 08:28
Hm, I think a `:this` alias sounds like a good idea.

I've found a workaround for my problem, but it's not as clean as I'd hoped. I'm creating a separate Validate object in the save method that takes care of image validation, and I moved the rules from initialize() to save() like I explained earlier. I think using a `:this` alias would have been a better solution in this case.

**Comment by banks** [comment] 2010-03-30 11:11
Where would this alias go? Would you add it to the Validate data? I guess that is relatively neat although not ideal. I guess we do something similar to get around the unique lazy saving issue.

**Comment by jonathangeiger** [comment] 2010-03-30 14:10
> Where would this alias go? Would you add it to the Validate data? I guess that is relatively neat although not ideal.

Yea, I know. Are there any other options you can think of?

**Comment by jonathangeiger** [comment] 2010-07-22 02:13
This has been fixed in unstable. Closing for now.

**Closed as completed by jonathangeiger** 2010-07-22 02:13 UTC
Labels: Feature Request
