### ISSUE TITLE
Correctly handle NULL and empty() values etc.

### ISSUE THREAD

**Issue by banks** [jonathangeiger/kohana-jelly#51] opened 2010-03-08 14:32 UTC
Allow fields to be NULLable in the database. Allow setting of 0 an '' to work with 'NULL' fields. Get $changed to work with all of this.

**Comment by banks** [comment] 2010-03-08 14:32
We discussed this in another issue but I thought I'd create it separately

**Comment by melvinmt** [comment] 2010-03-09 11:26
The solution for this is to strictly type test the conditional values on line 303 in jelly/model/core.php:

<pre>
            // Ensure data is really changed
            if ($field->in_db AND $this->_original[$field->name] == $value)
            {
                continue;
            }
</pre>

Should be:

<pre>
            // Ensure data is really changed
            if ($field->in_db AND $this->_original[$field->name] === $value)
            {
                continue;
            }
</pre>

**Comment by banks** [comment] 2010-03-09 11:30
> The solution for this is to strictly type test the conditional values

Actually that causes other issues. We used to do that but changed to == to solve another issue. The problem is more complex than it first appears and we are working out the best all-round solution.

**Comment by jjlegendre** [comment] 2010-03-10 02:42
I added a vote for this one only because it is causing me an issue with my current project.  I was using nulls in the DB to reflect empty values for fields and now I can't get Jelly to store a null when a string or timestamp is cleared by the user.  I'm working around it for now, but just wanted to cast my vote in the event you guys were weighing where how prioritize your work.

**Comment by banks** [comment] 2010-03-10 08:50
Thanks JJ, could you possibly describe your exact problem a little more - the more detail/examples the better really - we've kind of lost track of exactly what needs solving here. What can't you do that you should be able to do?

**Comment by SpadXIII** [comment] 2010-03-10 13:27
I'm having this issue as well. My model has a timestamp field which can be `NULL` in the database. In the form it's optional, so if left empty, I'd expect the field in de database to be `NULL` after saving. This is not the case: the field is `0` (int). The field type is an int which can be NULL.

The update-query that is Jelly generates sets the field to an _empty string_ instead of _NULL_.

Changing the fields, and their `set()` method could possibly solve this. I've added a quick test to the timestamp field in the `set` method which 'works':

```
if ($value === '')
{
    $value = NULL;
}
```

With this added, the update query sets the field to _NULL_ and not an _empty string_ anymore.

Perhaps fields should have an option to handle NULL-values similar to Sprig?

**Comment by banks** [comment] 2010-03-10 14:06
> Perhaps fields should have an option to handle NULL-values similar to Sprig?

That's what we are discussing here. My only thought about this is that it is perfectly valid to have a database column that can be NULL AND can contain the value 0. If we implement all empty() values get converted to NULL like Sprig does, that means you will never be able to set a nullable integer field to 0. Perhaps this isn't a real issue for people but I can think of situations where this may cause problems. Same goes for strings which can be NULL or ''.

The distinction in database terms is that NULL really indicates 'Completely unknown' rather than just 'empty' or 'default'. I may know that priority is 0 and want the row to work when I do `order_by('priority')` (ordering automatically removes rows with null values from results since, by definition, it is unknown where they come) but i may also want the field to be nullable so that rows for which there is no known priority can be marked as such and not just assumed to be 0.

Perhaps this is more of an edge case than it seems and the correct solution is to do as Sprig does and force you to create a custom field if you ever have this type of field.

We'll see. I think probably Sprig like NULL handling is the thing that will be best in general.

**Comment by SpadXIII** [comment] 2010-03-10 14:25
Adding a per-field option to nullify the empty values (false, 0, '') isn't a solution?

That way you can specify yourself whether you want the field to use NULL for empty values or not.

If you do want to use empty-values, set the nullify-option to false.

**Comment by melvinmt** [comment] 2010-03-10 14:58
> If we implement all empty() values get converted to NULL like Sprig does, that means you will never be able to set a nullable integer field to 0. Perhaps this isn't a real issue for people but I can think of situations where this may cause problems.

This is a real issue actually and it concerns the majority of the people. By default your MySQL table fields are NOT NULL and trying to insert a NULL value in a NOT NULL field will result in failure.

Also, like you said, there is a major difference in the integer `0` and `NULL` when you query the database. SELECT \* FROM table WHERE number = 0 will not return the same results as SELECT \* FROM table WHERE number is NULL 

I like the solution that SpadXIII suggested, that we can specify which fields are NOT NULL or NULL so these problems won't occur anymore.

**Comment by banks** [comment] 2010-03-10 16:53
> I like the solution that SpadXIII suggested, that we can specify which fields are NOT NULL or NULL so these problems won't occur anymore.

The problem is that _isn't_ what SpadXIII suggested! You are talking about a $null property that means that same as NULL/NOT NULL in a database column whereas SpadXIII wants $null property to decide which non-NULL values ( 0 , '', etc) should be converted to NULL.

My point is that the null property should mimic the database column property (as you suggest melvinmt) but most people actually want magic conversion of empty values.

Non of this is insurmountable, we just need to find the solution that works best all round!

**Comment by SpadXIII** [comment] 2010-03-10 19:12
My suggestion was to mimic the Sprig-method of handling empty-values. If this property is set to TRUE, every empty-value is converted to NULL, otherwise it's left alone.

It's not a solution for all problems, but perhaps a decent 'middle way' ?

Other than that, I don't see a (quick) solution for handling empty form fields without doing the checks manually (outside of the fields' validation-rules)

Having a field accept both 0 and NULL is great, but how would "leaving a form input of an integer field empty" translate into NULL and not 0? The $_POST contains an empty string, not a NULL-value...

ps. I'm just thinking out loud here, trying to help

**Comment by jjlegendre** [comment] 2010-03-11 01:55
Here is my example using code fragments:

Model

<pre>
'tags' => new Field_String (array (
    'label' => 'Tags'
)),
'createdon' => new Field_Timestamp (array (
    'label' => 'Created On',
    'pretty_format' => 'm/d/y',
    'auto_now_create' => true
)),
</pre>


Statements:

<pre>
$task = Jelly::select ('task', $id) ;
$task->tags = null ;
$task->createdon = null ;
$task->save () ;
</pre>


The string stores what I think is a 0 length string, but not a null.  In my last test the timestamp did store the null.  I understand that your implementation has issues that making solving this complex, but my real concern is that Jelly won't store what I'm telling it to store.  That is not ideal.  Is the other issue that is preventing you from using the literal compare (===) something that you could solve instead?  Let me know if you need more details.

**Comment by jonathangeiger** [comment] 2010-03-11 23:11
> My model has a timestamp field which can be NULL in the database. In the form it's optional, so if left empty, I'd expect the field in de database to be NULL after saving. This is not the case: the field is 0 (int). The field type is an int which can be NULL.

Just to put my two cents in here because I don't see it mentioned: Fields have a default property which defaults to an empty string. You can change this to NULL to have Jelly insert NULLs when you create the record. 

```
'field' => new Field_Timestamp(array('default' => NULL));
```

**Comment by jonathangeiger** [comment] 2010-03-11 23:23
> I understand that your implementation has issues that making solving this complex, but my real concern is that Jelly won't store what I'm telling it to store. That is not ideal. Is the other issue that is preventing you from using the literal compare (===) something that you could solve instead?

Could this be a non-issue now? I'll do some tests but I think this can be fixed.

In the current branch, maybe the == check can be strict (===). The original problem with having to do the == check was because the value wasn't converted to it's internally represented value when we compared to see if it'd actually changed. Recently, there was a commit where [the value is converted before it's compared](http://github.com/jonathangeiger/kohana-jelly/blob/8a2f75d92f820cee18bac81c33ba78a51a4d634b/classes/jelly/model/core.php#L300). I'll have to do some testing, but this could mean that this can be fixed very easily.

Also, about the NULL issue. I think we can implement this when we get the above working. This means fields can either be empty() or not empty() in which case they're set to NULL, or the application will manage the difference between NULL, 0, '', etc.

**Comment by jonathangeiger** [comment] 2010-03-11 23:30
This also means that we'll have to be careful about how field's process data. For example, Field_String always casts to a string. If Jelly is going to differentiate between NULL and '', we'll have to make sure not to cast NULLs to strings.

**Comment by jjlegendre** [comment] 2010-03-12 03:16
@Jon I'm not sure I followed all 3 of your posts, but I think the general idea is that you will revert to a strict check and that you will prevent jelly from casting Field_String to a string by default.  I'm not sure what you mean when you say "set to NULL, or the application will manage the difference between NULL, 0, '', etc."  I assume you mean that by default a field that had a value and then receives no value as part of a form field post will be set to NULL by default unless the application catches this and explicitly sets the field to something else.  Is that correct?

**Comment by SpadXIII** [comment] 2010-03-12 07:56
> Also, about the NULL issue. I think we can implement this when we get the above working. This means fields can either be empty() or not empty() in which case they're set to NULL, or the application will manage the difference between NULL, 0, '', etc.

would that be "set empty values to NULL by default for all fields" or only if you set an option in the field?

**Comment by glamorous** [comment] 2010-03-12 09:14
You could do the check for the casting this way and require people a proper use of the default value by setting it when necessary:

```
public function set($value)
{
    return ($value !== $this->default) ? (string)$value : $this->default;
}
```

**Comment by jonathangeiger** [comment] 2010-03-12 22:13
> but I think the general idea is that you will revert to a strict check and that you will prevent jelly from casting Field_String to a string by default

Yes. 

>  I assume you mean that by default a field that had a value and then receives no value as part of a form field post will be set to NULL by default unless the application catches this and explicitly sets the field to something else.

Not necessarily. The problem is that some fields will need to differentiate between NULL, 0, and '', while others will not. For those that do not, they can just set `null => true` (which will default to false) and let all empty values be converted to NULL. For fields that differentiate between NULL and 0 or  NULL and '' it will be the application's code to manage casting those values to the proper type. 

> would that be "set empty values to NULL by default for all fields" or only if you set an option in the field?

Only if you set an option in the field. You'll have to set `null => true` just as you do in Sprig. It will default to false. 

Does this make sense? Jelly cannot know the difference between NULL, 0,and '' to your application so the fields must not be casting NULLs to strings as they are now

**Comment by SpadXIII** [comment] 2010-03-13 09:30
That does make sense indeed. That way, you can either handle empty-values yourself or optionally have Jelly either auto-NULL these.

Casting the NULL's to values/strings/.. would have to be changed as well. If the value is NULL, Jelly should use NULL and not cast this to anything else.

**Comment by jonathangeiger** [comment] 2010-03-13 14:29
BTW, I've already got this done but don't have a proper computer to commit it on. I should be able to throw it up on Sunday.

**Comment by jjlegendre** [comment] 2010-03-18 20:31
I downloaded the latest build (bank's that says it fixed issue #58) and then I changed my field object to add <pre>'null' => true</pre>  I then tried it again and the value did not default to null when I set a Field_String to empty in the form post.  I've been in Disney World for the week so I wanted to check and see if you were able to commit.  Thanks!

**Comment by banks** [comment] 2010-03-18 21:03
@jj: really didn't follow that post. issue 58 is unrelated to this and no code for this is yet in master. Jon has put some code into unstable branch but presumably isn't yet happy with it as he's not merged it to master.

**Comment by jjlegendre** [comment] 2010-03-19 00:37
@banks: that was the answer to my question.  I just wanted to know if Jon had merged his changes into the master branch and per your post he has not.  Thanks.

**Comment by jonathangeiger** [comment] 2010-03-19 19:22
I've just merged unstable to master here. I consider this ready to go 5b3ee9e5e553926a28b9b240e3d62ad9c4beea37.

**Closed as completed by jonathangeiger** 2010-03-19 19:22 UTC
Labels: Bug
